import type { Track } from './types'

export const TRACKS: Track[] = [
  {
    id: 'baarishein',
    title: 'Baarishein',
    artist: 'Anuv Jain',
    coverUrl: '/Cover/Baarishein.jpg',
    audioUrl: '/songs/Baarishein.mp3',
    color: '#FF75A0',
    duration: 240,
    lyrics: [
      { time: 0, text: '♪ settle into a soft rainy evening ♪' },
      { time: 24, text: 'Let the quiet find you gently' },
      { time: 58, text: 'Keep a little light beside you' },
      { time: 96, text: 'There is beauty in the stillness' },
      { time: 140, text: 'Let the rain turn into memories' },
      { time: 190, text: 'Stay awhile inside this feeling' },
    ],
  },
  {
    id: 'arz-kiya-hai',
    title: 'Arz Kiya Hai',
    artist: 'Anuv Jain',
    coverUrl: '/Cover/Arz-kiya-hai.jpeg',
    audioUrl: '/songs/Arz-kiya-hai.mp3',
    color: '#FCE38A',
    duration: 220,
    lyrics: [
      { time: 0, text: '♪ a gentle thought begins to bloom ♪' },
      { time: 30, text: 'I leave a little hope with you' },
      { time: 72, text: 'May every open window bring peace' },
      { time: 118, text: 'Keep your kind heart close tonight' },
      { time: 174, text: 'And let tomorrow meet you softly' },
    ],
  },
  {
    id: 'tum-ho',
    title: 'Tum Ho',
    artist: 'Mohit Chauhan',
    coverUrl: '/Cover/Tum-ho.jpeg',
    audioUrl: '/songs/Tum-ho.mp3',
    color: '#B18CFF',
    duration: 300,
    lyrics: [
      { time: 0, text: '♪ a wide horizon opens slowly ♪' },
      { time: 42, text: 'You are the warmth inside the quiet' },
      { time: 104, text: 'Every familiar road feels new' },
      { time: 180, text: 'Keep this tender moment near' },
      { time: 252, text: 'Let the night carry you home' },
    ],
  },
  {
    id: 'the-night-we-met',
    title: 'The Night We Met',
    artist: 'Lord Huron',
    coverUrl: '/Cover/The-night-we-met.jpg',
    audioUrl: '/songs/The-night-we-met.mp3',
    color: '#4ECDC4',
    duration: 210,
    lyrics: [
      { time: 0, text: '♪ a memory drifts across the room ♪' },
      { time: 36, text: 'Some moments stay bright in the dark' },
      { time: 84, text: 'The past can glow without returning' },
      { time: 138, text: 'Carry the good into the morning' },
      { time: 184, text: 'Let the stars keep watch tonight' },
    ],
  },
  {
    id: 'lover',
    title: 'Lover',
    artist: 'Taylor Swift',
    coverUrl: '/Cover/Lover.jpeg',
    audioUrl: '/songs/Lover.mp3',
    color: '#FF9FBA',
    duration: 221,
    lyrics: [
      { time: 0, text: '♪ a warm room, a slow dance, a little forever ♪' },
      { time: 40, text: 'Make a home from ordinary hours' },
      { time: 92, text: 'Keep choosing joy in small ways' },
      { time: 148, text: 'Let the good days gather around you' },
      { time: 196, text: 'Stay close to what makes you glow' },
    ],
  },
  {
    id: 'line-without-a-hook',
    title: 'Line Without a Hook',
    artist: 'Ricky Montgomery',
    coverUrl: '/Cover/Line-without-a-hook.jpeg',
    audioUrl: '/songs/Line-without-a-hook.mp3',
    color: '#8BD9FF',
    duration: 240,
    lyrics: [
      { time: 0, text: '♪ a restless little melody takes flight ♪' },
      { time: 44, text: 'Some feelings refuse to be ordinary' },
      { time: 103, text: 'Even the tangled parts can be honest' },
      { time: 164, text: 'Find your rhythm and keep moving' },
      { time: 214, text: 'There is still a song ahead' },
    ],
  },
  {
    id: 'until-i-found-you',
    title: 'Until I Found You',
    artist: 'Stephen Sanchez',
    coverUrl: '/Cover/Until-i-found-you.png',
    audioUrl: '/songs/Until-i-found-you.mp3',
    color: '#FFD28A',
    duration: 157,
    lyrics: [
      { time: 0, text: '♪ golden lights and an old-fashioned sway ♪' },
      { time: 28, text: 'Somewhere, a brighter chapter waits' },
      { time: 64, text: 'Keep the wonder in your hands' },
      { time: 104, text: 'Let every heartbeat tell you yes' },
      { time: 136, text: 'Tonight feels like a lovely beginning' },
    ],
  },
]
